import React, { useEffect, useRef } from 'react';
import { Download, CheckCircle2, Code } from 'lucide-react';
import type { GeneratedSvg } from '../types';

interface SvgPreviewProps {
    data: GeneratedSvg | null;
}

export const SvgPreview: React.FC<SvgPreviewProps> = ({ data }) => {
    const [copied, setCopied] = React.useState(false);
    const containerRef = useRef<HTMLDivElement>(null);

    // Reset copied state when data changes
    useEffect(() => {
        setCopied(false);
    }, [data]);

    if (!data) return null;

    const handleDownload = () => {
        const blob = new Blob([data.content], { type: 'image/svg+xml' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `vectorcraft-${data.id}.svg`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    const handleCopyCode = () => {
        navigator.clipboard.writeText(data.content);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <div className="w-full max-w-4xl mx-auto mt-12 px-4 animate-in fade-in slide-in-from-bottom-8 duration-700">
            <div className="glass-panel rounded-2xl overflow-hidden shadow-2xl">
                {/* Toolbar */}
                <div className="flex items-center justify-between px-4 py-3 border-b border-dark-border bg-dark-card/50">
                    <h3 className="text-sm font-medium text-slate-300 truncate max-w-[150px] sm:max-w-xs">
                        Result: <span className="text-slate-500">"{data.prompt}"</span>
                    </h3>
                    <div className="flex gap-2">
                        <button
                            onClick={handleCopyCode}
                            className="p-2 text-slate-400 hover:text-white hover:bg-tech-500/10 rounded-lg transition-colors group relative"
                            title="Copy SVG Code">
                            {copied ? (
                                <CheckCircle2 className="w-5 h-5 text-green-400" />
                            ) : (
                                <Code className="w-5 h-5" />
                            )}
                        </button>
                        <button
                            onClick={handleDownload}
                            className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-white bg-tech-500 rounded-lg hover:bg-tech-600 transition-colors">
                            <Download className="w-4 h-4" />
                            <span className="hidden sm:inline">Download</span>
                        </button>
                    </div>
                </div>

                {/* Canvas Area */}
                <div className="p-8 flex items-center justify-center bg-dark-bg/80 min-h-[400px]">
                    {/* 
             Using dangerouslySetInnerHTML is intentional here as the content is generated by the LLM for the purpose of display.
           */}
                    <div
                        ref={containerRef}
                        className="w-full max-w-lg h-auto transition-all duration-500 transform hover:scale-[1.02] filter drop-shadow-2xl"
                        dangerouslySetInnerHTML={{ __html: data.content }}
                    />
                </div>

                {/* Metadata Footer */}
                <div className="px-4 py-2 bg-dark-bg border-t border-dark-border flex justify-between text-xs text-slate-600">
                    <span>Generated by Gemini 3 Pro</span>
                </div>
            </div>
        </div>
    );
};
