import type { ElementData } from './types';

export const ELEMENTS: ElementData[] = [
    {
        number: 1,
        symbol: 'H',
        name: 'Hydrogen',
        atomic_mass: 1.008,
        category: 'diatomic nonmetal',
        xpos: 1,
        ypos: 1,
        cpk_hex: 'ffffff',
        phase: 'Gas',
        discovered_by: 'Henry Cavendish',
        summary: 'Hydrogen is the chemical element with the symbol H and atomic number 1. Highly flammable.',
        reaction_type: 'Combustion'
    },
    {
        number: 2,
        symbol: 'He',
        name: 'Helium',
        atomic_mass: 4.0026,
        category: 'noble gas',
        xpos: 18,
        ypos: 1,
        cpk_hex: 'd9ffff',
        phase: 'Gas',
        discovered_by: 'Pierre Janssen',
        summary: 'Helium is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas.',
        reaction_type: 'Inert'
    },
    {
        number: 3,
        symbol: 'Li',
        name: 'Lithium',
        atomic_mass: 6.94,
        category: 'alkali metal',
        xpos: 1,
        ypos: 2,
        cpk_hex: 'cc80ff',
        phase: 'Solid',
        discovered_by: 'Johan August Arfwedson',
        summary: 'Lithium is a soft, silvery-white alkali metal.',
        crystal_structure: 'BCC',
        reaction_type: 'Oxidation'
    },
    {
        number: 4,
        symbol: 'Be',
        name: 'Beryllium',
        atomic_mass: 9.0122,
        category: 'alkaline earth metal',
        xpos: 2,
        ypos: 2,
        cpk_hex: 'c2ff00',
        phase: 'Solid',
        discovered_by: 'Louis Nicolas Vauquelin',
        summary: 'Beryllium is a steel-gray, strong, lightweight and brittle alkaline earth metal.',
        crystal_structure: 'HCP'
    },
    {
        number: 5,
        symbol: 'B',
        name: 'Boron',
        atomic_mass: 10.81,
        category: 'metalloid',
        xpos: 13,
        ypos: 2,
        cpk_hex: 'ffb5b5',
        phase: 'Solid',
        discovered_by: 'Joseph Louis Gay-Lussac',
        summary: "Boron is a metalloid found in the Earth's crust as borates."
    },
    {
        number: 6,
        symbol: 'C',
        name: 'Carbon',
        atomic_mass: 12.011,
        category: 'polyatomic nonmetal',
        xpos: 14,
        ypos: 2,
        cpk_hex: '909090',
        phase: 'Solid',
        discovered_by: 'Ancient',
        summary: 'Carbon forms diamonds and graphite. Essential for life.',
        crystal_structure: 'Diamond',
        reaction_type: 'Combustion'
    },
    {
        number: 7,
        symbol: 'N',
        name: 'Nitrogen',
        atomic_mass: 14.007,
        category: 'diatomic nonmetal',
        xpos: 15,
        ypos: 2,
        cpk_hex: '3050f8',
        phase: 'Gas',
        discovered_by: 'Daniel Rutherford',
        summary: "Nitrogen is a diatomic gas making up 78% of Earth's atmosphere."
    },
    {
        number: 8,
        symbol: 'O',
        name: 'Oxygen',
        atomic_mass: 15.999,
        category: 'diatomic nonmetal',
        xpos: 16,
        ypos: 2,
        cpk_hex: 'ff0d0d',
        phase: 'Gas',
        discovered_by: 'Carl Wilhelm Scheele',
        summary: 'Oxygen is a reactive nonmetal and an oxidizing agent.'
    },
    {
        number: 9,
        symbol: 'F',
        name: 'Fluorine',
        atomic_mass: 18.998,
        category: 'diatomic nonmetal',
        xpos: 17,
        ypos: 2,
        cpk_hex: '90e050',
        phase: 'Gas',
        discovered_by: 'André-Marie Ampère',
        summary: 'Fluorine is the most electronegative and reactive of all elements.'
    },
    {
        number: 10,
        symbol: 'Ne',
        name: 'Neon',
        atomic_mass: 20.18,
        category: 'noble gas',
        xpos: 18,
        ypos: 2,
        cpk_hex: 'b3e3f5',
        phase: 'Gas',
        discovered_by: 'Morris Travers',
        summary: 'Neon is a noble gas that glows reddish-orange in a discharge tube.'
    },
    {
        number: 11,
        symbol: 'Na',
        name: 'Sodium',
        atomic_mass: 22.99,
        category: 'alkali metal',
        xpos: 1,
        ypos: 3,
        cpk_hex: 'ab5cf2',
        phase: 'Solid',
        discovered_by: 'Humphry Davy',
        summary: 'Sodium is a soft, silvery-white, highly reactive alkali metal.',
        crystal_structure: 'BCC',
        reaction_type: 'Oxidation'
    },
    {
        number: 12,
        symbol: 'Mg',
        name: 'Magnesium',
        atomic_mass: 24.305,
        category: 'alkaline earth metal',
        xpos: 2,
        ypos: 3,
        cpk_hex: '8aff00',
        phase: 'Solid',
        discovered_by: 'Joseph Black',
        summary: 'Magnesium burns with a brilliant white light.',
        crystal_structure: 'HCP',
        reaction_type: 'Combustion'
    },
    {
        number: 13,
        symbol: 'Al',
        name: 'Aluminium',
        atomic_mass: 26.982,
        category: 'post-transition metal',
        xpos: 13,
        ypos: 3,
        cpk_hex: 'bfa6a6',
        phase: 'Solid',
        discovered_by: 'Hans Christian Ørsted',
        summary: 'Aluminium is a lightweight metal with high reflectivity.',
        crystal_structure: 'FCC'
    },
    {
        number: 14,
        symbol: 'Si',
        name: 'Silicon',
        atomic_mass: 28.085,
        category: 'metalloid',
        xpos: 14,
        ypos: 3,
        cpk_hex: 'f0c8a0',
        phase: 'Solid',
        discovered_by: 'Jöns Jacob Berzelius',
        summary: 'Silicon is a hard and brittle crystalline solid.'
    },
    {
        number: 15,
        symbol: 'P',
        name: 'Phosphorus',
        atomic_mass: 30.974,
        category: 'polyatomic nonmetal',
        xpos: 15,
        ypos: 3,
        cpk_hex: 'ff8000',
        phase: 'Solid',
        discovered_by: 'Hennig Brand',
        summary: 'Phosphorus exists in two main forms, white and red.'
    },
    {
        number: 16,
        symbol: 'S',
        name: 'Sulfur',
        atomic_mass: 32.06,
        category: 'polyatomic nonmetal',
        xpos: 16,
        ypos: 3,
        cpk_hex: 'ffff30',
        phase: 'Solid',
        discovered_by: 'Ancient',
        summary: 'Sulfur is a bright yellow crystalline solid.'
    },
    {
        number: 17,
        symbol: 'Cl',
        name: 'Chlorine',
        atomic_mass: 35.45,
        category: 'diatomic nonmetal',
        xpos: 17,
        ypos: 3,
        cpk_hex: '1ff01f',
        phase: 'Gas',
        discovered_by: 'Carl Wilhelm Scheele',
        summary: 'Chlorine is a yellow-green gas and powerful oxidizer.'
    },
    {
        number: 18,
        symbol: 'Ar',
        name: 'Argon',
        atomic_mass: 39.948,
        category: 'noble gas',
        xpos: 18,
        ypos: 3,
        cpk_hex: '80d1e3',
        phase: 'Gas',
        discovered_by: 'Lord Rayleigh',
        summary: "Argon is the third-most abundant gas in Earth's atmosphere."
    },
    {
        number: 19,
        symbol: 'K',
        name: 'Potassium',
        atomic_mass: 39.098,
        category: 'alkali metal',
        xpos: 1,
        ypos: 4,
        cpk_hex: '8f40d4',
        phase: 'Solid',
        discovered_by: 'Humphry Davy',
        summary: 'Silvery-white metal that reacts violently with water.',
        crystal_structure: 'BCC'
    },
    {
        number: 20,
        symbol: 'Ca',
        name: 'Calcium',
        atomic_mass: 40.078,
        category: 'alkaline earth metal',
        xpos: 2,
        ypos: 4,
        cpk_hex: '3dff00',
        phase: 'Solid',
        discovered_by: 'Humphry Davy',
        summary: 'Calcium is essential for bone health.',
        crystal_structure: 'FCC'
    },
    {
        number: 21,
        symbol: 'Sc',
        name: 'Scandium',
        atomic_mass: 44.956,
        category: 'transition metal',
        xpos: 3,
        ypos: 4,
        cpk_hex: 'e6e6e6',
        phase: 'Solid',
        discovered_by: 'Lars Fredrik Nilson',
        summary: 'Silvery-white metallic transition element.',
        crystal_structure: 'HCP'
    },
    {
        number: 22,
        symbol: 'Ti',
        name: 'Titanium',
        atomic_mass: 47.867,
        category: 'transition metal',
        xpos: 4,
        ypos: 4,
        cpk_hex: 'bfc2c7',
        phase: 'Solid',
        discovered_by: 'William Gregor',
        summary: 'Known for strength and corrosion resistance.',
        crystal_structure: 'HCP'
    },
    {
        number: 23,
        symbol: 'V',
        name: 'Vanadium',
        atomic_mass: 50.942,
        category: 'transition metal',
        xpos: 5,
        ypos: 4,
        cpk_hex: 'a6a6ab',
        phase: 'Solid',
        discovered_by: 'Andrés Manuel del Río',
        summary: 'Hard, silvery-grey, ductile transition metal.',
        crystal_structure: 'BCC'
    },
    {
        number: 24,
        symbol: 'Cr',
        name: 'Chromium',
        atomic_mass: 51.996,
        category: 'transition metal',
        xpos: 6,
        ypos: 4,
        cpk_hex: '8a99c7',
        phase: 'Solid',
        discovered_by: 'Louis Nicolas Vauquelin',
        summary: 'Steely-grey, hard and brittle metal.',
        crystal_structure: 'BCC'
    },
    {
        number: 25,
        symbol: 'Mn',
        name: 'Manganese',
        atomic_mass: 54.938,
        category: 'transition metal',
        xpos: 7,
        ypos: 4,
        cpk_hex: '9c7ac7',
        phase: 'Solid',
        discovered_by: 'Torbern Olof Bergman',
        summary: 'Essential to iron and steel production.'
    },
    {
        number: 26,
        symbol: 'Fe',
        name: 'Iron',
        atomic_mass: 55.845,
        category: 'transition metal',
        xpos: 8,
        ypos: 4,
        cpk_hex: 'e06633',
        phase: 'Solid',
        discovered_by: 'Ancient',
        summary: 'Most abundant element on Earth by mass.',
        crystal_structure: 'BCC',
        reaction_type: 'Oxidation'
    },
    {
        number: 27,
        symbol: 'Co',
        name: 'Cobalt',
        atomic_mass: 58.933,
        category: 'transition metal',
        xpos: 9,
        ypos: 4,
        cpk_hex: 'f090a0',
        phase: 'Solid',
        discovered_by: 'Georg Brandt',
        summary: 'Used in high-strength alloys.',
        crystal_structure: 'HCP'
    },
    {
        number: 28,
        symbol: 'Ni',
        name: 'Nickel',
        atomic_mass: 58.693,
        category: 'transition metal',
        xpos: 10,
        ypos: 4,
        cpk_hex: '50d050',
        phase: 'Solid',
        discovered_by: 'Axel Fredrik Cronstedt',
        summary: 'Silvery-white lustrous metal with golden tinge.',
        crystal_structure: 'FCC'
    },
    {
        number: 29,
        symbol: 'Cu',
        name: 'Copper',
        atomic_mass: 63.546,
        category: 'transition metal',
        xpos: 11,
        ypos: 4,
        cpk_hex: 'c88033',
        phase: 'Solid',
        discovered_by: 'Ancient',
        summary: 'Soft, malleable, and ductile metal.',
        crystal_structure: 'FCC'
    },
    {
        number: 30,
        symbol: 'Zn',
        name: 'Zinc',
        atomic_mass: 65.38,
        category: 'transition metal',
        xpos: 12,
        ypos: 4,
        cpk_hex: '7d80b0',
        phase: 'Solid',
        discovered_by: 'Ancient',
        summary: 'Used to galvanize steel.',
        crystal_structure: 'HCP'
    },
    {
        number: 31,
        symbol: 'Ga',
        name: 'Gallium',
        atomic_mass: 69.723,
        category: 'post-transition metal',
        xpos: 13,
        ypos: 4,
        cpk_hex: 'c28f8f',
        phase: 'Solid',
        discovered_by: 'Paul-Émile Lecoq de Boisbaudran',
        summary: 'Melts at room temperature.'
    },
    {
        number: 32,
        symbol: 'Ge',
        name: 'Germanium',
        atomic_mass: 72.63,
        category: 'metalloid',
        xpos: 14,
        ypos: 4,
        cpk_hex: '668f8f',
        phase: 'Solid',
        discovered_by: 'Clemens Winkler',
        summary: 'Important semiconductor material.'
    },
    {
        number: 33,
        symbol: 'As',
        name: 'Arsenic',
        atomic_mass: 74.922,
        category: 'metalloid',
        xpos: 15,
        ypos: 4,
        cpk_hex: 'bd80e3',
        phase: 'Solid',
        discovered_by: 'Bronze Age',
        summary: 'Well known as a potent poison.'
    },
    {
        number: 34,
        symbol: 'Se',
        name: 'Selenium',
        atomic_mass: 78.971,
        category: 'polyatomic nonmetal',
        xpos: 16,
        ypos: 4,
        cpk_hex: 'ffa100',
        phase: 'Solid',
        discovered_by: 'Jöns Jacob Berzelius',
        summary: 'Used in photocells and solar cells.'
    },
    {
        number: 35,
        symbol: 'Br',
        name: 'Bromine',
        atomic_mass: 79.904,
        category: 'diatomic nonmetal',
        xpos: 17,
        ypos: 4,
        cpk_hex: 'a62929',
        phase: 'Liquid',
        discovered_by: 'Antoine Jérôme Balard',
        summary: 'Fuming red-brown liquid.'
    },
    {
        number: 36,
        symbol: 'Kr',
        name: 'Krypton',
        atomic_mass: 83.798,
        category: 'noble gas',
        xpos: 18,
        ypos: 4,
        cpk_hex: '5cb8d1',
        phase: 'Gas',
        discovered_by: 'William Ramsay',
        summary: 'Noble gas used in lighting.'
    },
    {
        number: 37,
        symbol: 'Rb',
        name: 'Rubidium',
        atomic_mass: 85.468,
        category: 'alkali metal',
        xpos: 1,
        ypos: 5,
        cpk_hex: '702eb0',
        phase: 'Solid',
        discovered_by: 'Robert Bunsen',
        summary: 'Highly reactive alkali metal.',
        crystal_structure: 'BCC'
    },
    {
        number: 38,
        symbol: 'Sr',
        name: 'Strontium',
        atomic_mass: 87.62,
        category: 'alkaline earth metal',
        xpos: 2,
        ypos: 5,
        cpk_hex: '00ff00',
        phase: 'Solid',
        discovered_by: 'Adair Crawford',
        summary: 'Used in fireworks for red color.',
        crystal_structure: 'FCC'
    },
    {
        number: 39,
        symbol: 'Y',
        name: 'Yttrium',
        atomic_mass: 88.906,
        category: 'transition metal',
        xpos: 3,
        ypos: 5,
        cpk_hex: '94ffff',
        phase: 'Solid',
        discovered_by: 'Johan Gadolin',
        summary: 'Rare-earth transition metal.',
        crystal_structure: 'HCP'
    },
    {
        number: 40,
        symbol: 'Zr',
        name: 'Zirconium',
        atomic_mass: 91.224,
        category: 'transition metal',
        xpos: 4,
        ypos: 5,
        cpk_hex: '94e0e0',
        phase: 'Solid',
        discovered_by: 'Martin Heinrich Klaproth',
        summary: 'High resistance to corrosion.',
        crystal_structure: 'HCP'
    },
    {
        number: 41,
        symbol: 'Nb',
        name: 'Niobium',
        atomic_mass: 92.906,
        category: 'transition metal',
        xpos: 5,
        ypos: 5,
        cpk_hex: '73c2c9',
        phase: 'Solid',
        discovered_by: 'Charles Hatchett',
        summary: 'Used in superconducting magnets.',
        crystal_structure: 'BCC'
    },
    {
        number: 42,
        symbol: 'Mo',
        name: 'Molybdenum',
        atomic_mass: 95.95,
        category: 'transition metal',
        xpos: 6,
        ypos: 5,
        cpk_hex: '54b5b5',
        phase: 'Solid',
        discovered_by: 'Carl Wilhelm Scheele',
        summary: 'Used in steel alloys.',
        crystal_structure: 'BCC'
    },
    {
        number: 43,
        symbol: 'Tc',
        name: 'Technetium',
        atomic_mass: 98,
        category: 'transition metal',
        xpos: 7,
        ypos: 5,
        cpk_hex: '3b9e9e',
        phase: 'Solid',
        discovered_by: 'Emilio Segrè',
        summary: 'First element to be produced artificially.'
    },
    {
        number: 44,
        symbol: 'Ru',
        name: 'Ruthenium',
        atomic_mass: 101.07,
        category: 'transition metal',
        xpos: 8,
        ypos: 5,
        cpk_hex: '248f8f',
        phase: 'Solid',
        discovered_by: 'Karl Ernst Claus',
        summary: 'Rare transition metal.',
        crystal_structure: 'HCP'
    },
    {
        number: 45,
        symbol: 'Rh',
        name: 'Rhodium',
        atomic_mass: 102.91,
        category: 'transition metal',
        xpos: 9,
        ypos: 5,
        cpk_hex: '0a7d8c',
        phase: 'Solid',
        discovered_by: 'William Hyde Wollaston',
        summary: 'Extremely rare precious metal.',
        crystal_structure: 'FCC'
    },
    {
        number: 46,
        symbol: 'Pd',
        name: 'Palladium',
        atomic_mass: 106.42,
        category: 'transition metal',
        xpos: 10,
        ypos: 5,
        cpk_hex: '006985',
        phase: 'Solid',
        discovered_by: 'William Hyde Wollaston',
        summary: 'Key in catalytic converters.',
        crystal_structure: 'FCC'
    },
    {
        number: 47,
        symbol: 'Ag',
        name: 'Silver',
        atomic_mass: 107.87,
        category: 'transition metal',
        xpos: 11,
        ypos: 5,
        cpk_hex: 'c0c0c0',
        phase: 'Solid',
        discovered_by: 'Ancient',
        summary: 'Highest electrical conductivity.',
        crystal_structure: 'FCC'
    },
    {
        number: 48,
        symbol: 'Cd',
        name: 'Cadmium',
        atomic_mass: 112.41,
        category: 'transition metal',
        xpos: 12,
        ypos: 5,
        cpk_hex: 'ffd98f',
        phase: 'Solid',
        discovered_by: 'Karl Hermann',
        summary: 'Used in rechargeable batteries.',
        crystal_structure: 'HCP'
    },
    {
        number: 49,
        symbol: 'In',
        name: 'Indium',
        atomic_mass: 114.82,
        category: 'post-transition metal',
        xpos: 13,
        ypos: 5,
        cpk_hex: 'a67573',
        phase: 'Solid',
        discovered_by: 'Ferdinand Reich',
        summary: 'Soft metal used in touchscreens.'
    },
    {
        number: 50,
        symbol: 'Sn',
        name: 'Tin',
        atomic_mass: 118.71,
        category: 'post-transition metal',
        xpos: 14,
        ypos: 5,
        cpk_hex: '668080',
        phase: 'Solid',
        discovered_by: 'Ancient',
        summary: 'Silvery-white metal.'
    },
    {
        number: 51,
        symbol: 'Sb',
        name: 'Antimony',
        atomic_mass: 121.76,
        category: 'metalloid',
        xpos: 15,
        ypos: 5,
        cpk_hex: '9e63b5',
        phase: 'Solid',
        discovered_by: 'Ancient',
        summary: 'Used in fire retardants.'
    },
    {
        number: 52,
        symbol: 'Te',
        name: 'Tellurium',
        atomic_mass: 127.6,
        category: 'metalloid',
        xpos: 16,
        ypos: 5,
        cpk_hex: 'd47a00',
        phase: 'Solid',
        discovered_by: 'Franz Müller',
        summary: 'Rare silvery-white metalloid.'
    },
    {
        number: 53,
        symbol: 'I',
        name: 'Iodine',
        atomic_mass: 126.9,
        category: 'diatomic nonmetal',
        xpos: 17,
        ypos: 5,
        cpk_hex: '940094',
        phase: 'Solid',
        discovered_by: 'Bernard Courtois',
        summary: 'Lustrous purple-black solid.'
    },
    {
        number: 54,
        symbol: 'Xe',
        name: 'Xenon',
        atomic_mass: 131.29,
        category: 'noble gas',
        xpos: 18,
        ypos: 5,
        cpk_hex: '429eb0',
        phase: 'Gas',
        discovered_by: 'William Ramsay',
        summary: 'Denser than air, noble gas.'
    },
    {
        number: 55,
        symbol: 'Cs',
        name: 'Cesium',
        atomic_mass: 132.91,
        category: 'alkali metal',
        xpos: 1,
        ypos: 6,
        cpk_hex: '57178f',
        phase: 'Solid',
        discovered_by: 'Robert Bunsen',
        summary: 'Extremely reactive metal.',
        crystal_structure: 'BCC'
    },
    {
        number: 56,
        symbol: 'Ba',
        name: 'Barium',
        atomic_mass: 137.33,
        category: 'alkaline earth metal',
        xpos: 2,
        ypos: 6,
        cpk_hex: '00c900',
        phase: 'Solid',
        discovered_by: 'Carl Wilhelm Scheele',
        summary: 'Highly reactive metal.',
        crystal_structure: 'BCC'
    },
    {
        number: 57,
        symbol: 'La',
        name: 'Lanthanum',
        atomic_mass: 138.91,
        category: 'lanthanide',
        xpos: 4,
        ypos: 9,
        cpk_hex: '70d4ff',
        phase: 'Solid',
        discovered_by: 'Carl Gustaf Mosander',
        summary: 'Silvery-white metallic element.',
        crystal_structure: 'HCP'
    },
    {
        number: 58,
        symbol: 'Ce',
        name: 'Cerium',
        atomic_mass: 140.12,
        category: 'lanthanide',
        xpos: 5,
        ypos: 9,
        cpk_hex: 'ffffc7',
        phase: 'Solid',
        discovered_by: 'Martin Klaproth',
        summary: 'Most abundant rare-earth.',
        crystal_structure: 'FCC'
    },
    {
        number: 59,
        symbol: 'Pr',
        name: 'Praseodymium',
        atomic_mass: 140.91,
        category: 'lanthanide',
        xpos: 6,
        ypos: 9,
        cpk_hex: 'd9ffc7',
        phase: 'Solid',
        discovered_by: 'Carl von Welsbach',
        summary: 'Soft silvery metal.',
        crystal_structure: 'HCP'
    },
    {
        number: 60,
        symbol: 'Nd',
        name: 'Neodymium',
        atomic_mass: 144.24,
        category: 'lanthanide',
        xpos: 7,
        ypos: 9,
        cpk_hex: 'c7ffc7',
        phase: 'Solid',
        discovered_by: 'Carl von Welsbach',
        summary: 'Strong permanent magnets.',
        crystal_structure: 'HCP'
    },
    {
        number: 61,
        symbol: 'Pm',
        name: 'Promethium',
        atomic_mass: 145,
        category: 'lanthanide',
        xpos: 8,
        ypos: 9,
        cpk_hex: 'a3ffc7',
        phase: 'Solid',
        discovered_by: 'Wu',
        summary: 'All isotopes are radioactive.'
    },
    {
        number: 62,
        symbol: 'Sm',
        name: 'Samarium',
        atomic_mass: 150.36,
        category: 'lanthanide',
        xpos: 9,
        ypos: 9,
        cpk_hex: '8fffc7',
        phase: 'Solid',
        discovered_by: 'Lecoq de Boisbaudran',
        summary: 'Moderately hard silvery metal.'
    },
    {
        number: 63,
        symbol: 'Eu',
        name: 'Europium',
        atomic_mass: 151.96,
        category: 'lanthanide',
        xpos: 10,
        ypos: 9,
        cpk_hex: '61ffc7',
        phase: 'Solid',
        discovered_by: 'Eugène Demarçay',
        summary: 'Most reactive rare-earth.',
        crystal_structure: 'BCC'
    },
    {
        number: 64,
        symbol: 'Gd',
        name: 'Gadolinium',
        atomic_mass: 157.25,
        category: 'lanthanide',
        xpos: 11,
        ypos: 9,
        cpk_hex: '45ffc7',
        phase: 'Solid',
        discovered_by: 'Marignac',
        summary: 'Used in MRI contrast agents.',
        crystal_structure: 'HCP'
    },
    {
        number: 65,
        symbol: 'Tb',
        name: 'Terbium',
        atomic_mass: 158.93,
        category: 'lanthanide',
        xpos: 12,
        ypos: 9,
        cpk_hex: '30ffc7',
        phase: 'Solid',
        discovered_by: 'Mosander',
        summary: 'Rare earth metal.',
        crystal_structure: 'HCP'
    },
    {
        number: 66,
        symbol: 'Dy',
        name: 'Dysprosium',
        atomic_mass: 162.5,
        category: 'lanthanide',
        xpos: 13,
        ypos: 9,
        cpk_hex: '1fffc7',
        phase: 'Solid',
        discovered_by: 'Boisbaudran',
        summary: 'Used in high power magnets.',
        crystal_structure: 'HCP'
    },
    {
        number: 67,
        symbol: 'Ho',
        name: 'Holmium',
        atomic_mass: 164.93,
        category: 'lanthanide',
        xpos: 14,
        ypos: 9,
        cpk_hex: '00ff9c',
        phase: 'Solid',
        discovered_by: 'Delafontaine',
        summary: 'Highest magnetic strength.',
        crystal_structure: 'HCP'
    },
    {
        number: 68,
        symbol: 'Er',
        name: 'Erbium',
        atomic_mass: 167.26,
        category: 'lanthanide',
        xpos: 15,
        ypos: 9,
        cpk_hex: '00e675',
        phase: 'Solid',
        discovered_by: 'Mosander',
        summary: 'Pink ions used in lasers.',
        crystal_structure: 'HCP'
    },
    {
        number: 69,
        symbol: 'Tm',
        name: 'Thulium',
        atomic_mass: 168.93,
        category: 'lanthanide',
        xpos: 16,
        ypos: 9,
        cpk_hex: '00d452',
        phase: 'Solid',
        discovered_by: 'Cleve',
        summary: 'Rare earth element.',
        crystal_structure: 'HCP'
    },
    {
        number: 70,
        symbol: 'Yb',
        name: 'Ytterbium',
        atomic_mass: 173.05,
        category: 'lanthanide',
        xpos: 17,
        ypos: 9,
        cpk_hex: '00bf38',
        phase: 'Solid',
        discovered_by: 'Marignac',
        summary: 'Soft and malleable.',
        crystal_structure: 'FCC'
    },
    {
        number: 71,
        symbol: 'Lu',
        name: 'Lutetium',
        atomic_mass: 174.97,
        category: 'lanthanide',
        xpos: 18,
        ypos: 9,
        cpk_hex: '00ab24',
        phase: 'Solid',
        discovered_by: 'Urbain',
        summary: 'Hardest rare-earth metal.',
        crystal_structure: 'HCP'
    },
    {
        number: 72,
        symbol: 'Hf',
        name: 'Hafnium',
        atomic_mass: 178.49,
        category: 'transition metal',
        xpos: 4,
        ypos: 6,
        cpk_hex: '4dc2ff',
        phase: 'Solid',
        discovered_by: 'Dirk Coster',
        summary: 'Lustrous silvery grey metal.',
        crystal_structure: 'HCP'
    },
    {
        number: 73,
        symbol: 'Ta',
        name: 'Tantalum',
        atomic_mass: 180.95,
        category: 'transition metal',
        xpos: 5,
        ypos: 6,
        cpk_hex: '4da6ff',
        phase: 'Solid',
        discovered_by: 'Ekeberg',
        summary: 'Rare and hard metal.',
        crystal_structure: 'BCC'
    },
    {
        number: 74,
        symbol: 'W',
        name: 'Tungsten',
        atomic_mass: 183.84,
        category: 'transition metal',
        xpos: 6,
        ypos: 6,
        cpk_hex: '2194d6',
        phase: 'Solid',
        discovered_by: 'Scheele',
        summary: 'Highest melting point of metals.',
        crystal_structure: 'BCC'
    },
    {
        number: 75,
        symbol: 'Re',
        name: 'Rhenium',
        atomic_mass: 186.21,
        category: 'transition metal',
        xpos: 7,
        ypos: 6,
        cpk_hex: '267daa',
        phase: 'Solid',
        discovered_by: 'Ogawa',
        summary: 'One of the rarest elements.',
        crystal_structure: 'HCP'
    },
    {
        number: 76,
        symbol: 'Os',
        name: 'Osmium',
        atomic_mass: 190.23,
        category: 'transition metal',
        xpos: 8,
        ypos: 6,
        cpk_hex: '266696',
        phase: 'Solid',
        discovered_by: 'Tennant',
        summary: 'Densest natural element.',
        crystal_structure: 'HCP'
    },
    {
        number: 77,
        symbol: 'Ir',
        name: 'Iridium',
        atomic_mass: 192.22,
        category: 'transition metal',
        xpos: 9,
        ypos: 6,
        cpk_hex: '175487',
        phase: 'Solid',
        discovered_by: 'Tennant',
        summary: 'Most corrosion resistant.',
        crystal_structure: 'FCC'
    },
    {
        number: 78,
        symbol: 'Pt',
        name: 'Platinum',
        atomic_mass: 195.08,
        category: 'transition metal',
        xpos: 10,
        ypos: 6,
        cpk_hex: 'd0d0e0',
        phase: 'Solid',
        discovered_by: 'Ulloa',
        summary: 'Precious metal.',
        crystal_structure: 'FCC'
    },
    {
        number: 79,
        symbol: 'Au',
        name: 'Gold',
        atomic_mass: 196.97,
        category: 'transition metal',
        xpos: 11,
        ypos: 6,
        cpk_hex: 'ffd123',
        phase: 'Solid',
        discovered_by: 'Ancient',
        summary: 'Most malleable of all metals.',
        crystal_structure: 'FCC',
        reaction_type: 'Inert'
    },
    {
        number: 80,
        symbol: 'Hg',
        name: 'Mercury',
        atomic_mass: 200.59,
        category: 'transition metal',
        xpos: 12,
        ypos: 6,
        cpk_hex: 'b8b8d0',
        phase: 'Liquid',
        discovered_by: 'Ancient',
        summary: 'Only liquid metal at room temp.'
    },
    {
        number: 81,
        symbol: 'Tl',
        name: 'Thallium',
        atomic_mass: 204.38,
        category: 'post-transition metal',
        xpos: 13,
        ypos: 6,
        cpk_hex: 'a6544d',
        phase: 'Solid',
        discovered_by: 'Crookes',
        summary: 'Highly toxic metal.',
        crystal_structure: 'HCP'
    },
    {
        number: 82,
        symbol: 'Pb',
        name: 'Lead',
        atomic_mass: 207.2,
        category: 'post-transition metal',
        xpos: 14,
        ypos: 6,
        cpk_hex: '575961',
        phase: 'Solid',
        discovered_by: 'Ancient',
        summary: 'Heavy and dense metal.',
        crystal_structure: 'FCC'
    },
    {
        number: 83,
        symbol: 'Bi',
        name: 'Bismuth',
        atomic_mass: 208.98,
        category: 'post-transition metal',
        xpos: 15,
        ypos: 6,
        cpk_hex: '9e4fb5',
        phase: 'Solid',
        discovered_by: 'Geoffroy',
        summary: 'Brittle pinkish metal.'
    },
    {
        number: 84,
        symbol: 'Po',
        name: 'Polonium',
        atomic_mass: 209,
        category: 'post-transition metal',
        xpos: 16,
        ypos: 6,
        cpk_hex: 'ab5c00',
        phase: 'Solid',
        discovered_by: 'Curie',
        summary: 'Highly radioactive metal.',
        crystal_structure: 'SimpleCubic'
    },
    {
        number: 85,
        symbol: 'At',
        name: 'Astatine',
        atomic_mass: 210,
        category: 'metalloid',
        xpos: 17,
        ypos: 6,
        cpk_hex: '754f45',
        phase: 'Solid',
        discovered_by: 'Corson',
        summary: 'Rarest natural element.'
    },
    {
        number: 86,
        symbol: 'Rn',
        name: 'Radon',
        atomic_mass: 222,
        category: 'noble gas',
        xpos: 18,
        ypos: 6,
        cpk_hex: '428296',
        phase: 'Gas',
        discovered_by: 'Dorn',
        summary: 'Radioactive noble gas.'
    },
    {
        number: 87,
        symbol: 'Fr',
        name: 'Francium',
        atomic_mass: 223,
        category: 'alkali metal',
        xpos: 1,
        ypos: 7,
        cpk_hex: '420066',
        phase: 'Solid',
        discovered_by: 'Marguerite Perey',
        summary: 'Extremely radioactive.',
        crystal_structure: 'BCC'
    },
    {
        number: 88,
        symbol: 'Ra',
        name: 'Radium',
        atomic_mass: 226,
        category: 'alkaline earth metal',
        xpos: 2,
        ypos: 7,
        cpk_hex: '006600',
        phase: 'Solid',
        discovered_by: 'Marie Curie',
        summary: 'Used in luminous paints.',
        crystal_structure: 'BCC'
    },
    {
        number: 89,
        symbol: 'Ac',
        name: 'Actinium',
        atomic_mass: 227,
        category: 'actinide',
        xpos: 4,
        ypos: 10,
        cpk_hex: '70abff',
        phase: 'Solid',
        discovered_by: 'Friedrich Oskar Giesel',
        summary: 'Soft silvery radioactive metal.',
        crystal_structure: 'FCC'
    },
    {
        number: 90,
        symbol: 'Th',
        name: 'Thorium',
        atomic_mass: 232.04,
        category: 'actinide',
        xpos: 5,
        ypos: 10,
        cpk_hex: '00baff',
        phase: 'Solid',
        discovered_by: 'Berzelius',
        summary: 'Weakly radioactive metal.',
        crystal_structure: 'FCC'
    },
    {
        number: 91,
        symbol: 'Pa',
        name: 'Protactinium',
        atomic_mass: 231.04,
        category: 'actinide',
        xpos: 6,
        ypos: 10,
        cpk_hex: '00a1ff',
        phase: 'Solid',
        discovered_by: 'Crookes',
        summary: 'Dense silvery-grey actinide.',
        crystal_structure: 'BCC'
    },
    {
        number: 92,
        symbol: 'U',
        name: 'Uranium',
        atomic_mass: 238.03,
        category: 'actinide',
        xpos: 7,
        ypos: 10,
        cpk_hex: '008fff',
        phase: 'Solid',
        discovered_by: 'Klaproth',
        summary: 'Used in nuclear power.'
    },
    {
        number: 93,
        symbol: 'Np',
        name: 'Neptunium',
        atomic_mass: 237,
        category: 'actinide',
        xpos: 8,
        ypos: 10,
        cpk_hex: '0080ff',
        phase: 'Solid',
        discovered_by: 'McMillan',
        summary: 'Transuranic radioactive element.'
    },
    {
        number: 94,
        symbol: 'Pu',
        name: 'Plutonium',
        atomic_mass: 244,
        category: 'actinide',
        xpos: 9,
        ypos: 10,
        cpk_hex: '006bff',
        phase: 'Solid',
        discovered_by: 'Seaborg',
        summary: 'Radioactive actinide metal.'
    },
    {
        number: 95,
        symbol: 'Am',
        name: 'Americium',
        atomic_mass: 243,
        category: 'actinide',
        xpos: 10,
        ypos: 10,
        cpk_hex: '545cf2',
        phase: 'Solid',
        discovered_by: 'Seaborg',
        summary: 'Used in smoke detectors.'
    },
    {
        number: 96,
        symbol: 'Cm',
        name: 'Curium',
        atomic_mass: 247,
        category: 'actinide',
        xpos: 11,
        ypos: 10,
        cpk_hex: '785ce3',
        phase: 'Solid',
        discovered_by: 'Seaborg',
        summary: 'Named after the Curies.'
    },
    {
        number: 97,
        symbol: 'Bk',
        name: 'Berkelium',
        atomic_mass: 247,
        category: 'actinide',
        xpos: 12,
        ypos: 10,
        cpk_hex: '8a4fe3',
        phase: 'Solid',
        discovered_by: 'Seaborg',
        summary: 'Named after Berkeley.'
    },
    {
        number: 98,
        symbol: 'Cf',
        name: 'Californium',
        atomic_mass: 251,
        category: 'actinide',
        xpos: 13,
        ypos: 10,
        cpk_hex: 'a136d4',
        phase: 'Solid',
        discovered_by: 'Seaborg',
        summary: 'Radioactive element.'
    },
    {
        number: 99,
        symbol: 'Es',
        name: 'Einsteinium',
        atomic_mass: 252,
        category: 'actinide',
        xpos: 14,
        ypos: 10,
        cpk_hex: 'b31fd4',
        phase: 'Solid',
        discovered_by: 'Ghiorso',
        summary: 'Named after Einstein.'
    },
    {
        number: 100,
        symbol: 'Fm',
        name: 'Fermium',
        atomic_mass: 257,
        category: 'actinide',
        xpos: 15,
        ypos: 10,
        cpk_hex: 'b31fba',
        phase: 'Solid',
        discovered_by: 'Ghiorso',
        summary: 'Named after Fermi.'
    },
    {
        number: 101,
        symbol: 'Md',
        name: 'Mendelevium',
        atomic_mass: 258,
        category: 'actinide',
        xpos: 16,
        ypos: 10,
        cpk_hex: 'b30da6',
        phase: 'Solid',
        discovered_by: 'Ghiorso',
        summary: 'Named after Mendeleev.'
    },
    {
        number: 102,
        symbol: 'No',
        name: 'Nobelium',
        atomic_mass: 259,
        category: 'actinide',
        xpos: 17,
        ypos: 10,
        cpk_hex: 'bd0d87',
        phase: 'Solid',
        discovered_by: 'Nobel Institute',
        summary: 'Named after Nobel.'
    },
    {
        number: 103,
        symbol: 'Lr',
        name: 'Lawrencium',
        atomic_mass: 262,
        category: 'actinide',
        xpos: 18,
        ypos: 10,
        cpk_hex: 'c70066',
        phase: 'Solid',
        discovered_by: 'Ghiorso',
        summary: 'Named after Lawrence.'
    },
    {
        number: 104,
        symbol: 'Rf',
        name: 'Rutherfordium',
        atomic_mass: 267,
        category: 'transition metal',
        xpos: 4,
        ypos: 7,
        cpk_hex: 'cc0059',
        phase: 'Solid',
        discovered_by: 'JINR',
        summary: 'Synthetic radioactive element.'
    },
    {
        number: 105,
        symbol: 'Db',
        name: 'Dubnium',
        atomic_mass: 268,
        category: 'transition metal',
        xpos: 5,
        ypos: 7,
        cpk_hex: 'd1004f',
        phase: 'Solid',
        discovered_by: 'JINR',
        summary: 'Synthetic radioactive element.'
    },
    {
        number: 106,
        symbol: 'Sg',
        name: 'Seaborgium',
        atomic_mass: 269,
        category: 'transition metal',
        xpos: 6,
        ypos: 7,
        cpk_hex: 'd90045',
        phase: 'Solid',
        discovered_by: 'Berkeley',
        summary: 'Synthetic radioactive element.'
    },
    {
        number: 107,
        symbol: 'Bh',
        name: 'Bohrium',
        atomic_mass: 270,
        category: 'transition metal',
        xpos: 7,
        ypos: 7,
        cpk_hex: 'e00038',
        phase: 'Solid',
        discovered_by: 'GSI',
        summary: 'Synthetic radioactive element.'
    },
    {
        number: 108,
        symbol: 'Hs',
        name: 'Hassium',
        atomic_mass: 269,
        category: 'transition metal',
        xpos: 8,
        ypos: 7,
        cpk_hex: 'e6002e',
        phase: 'Solid',
        discovered_by: 'GSI',
        summary: 'Synthetic radioactive element.'
    },
    {
        number: 109,
        symbol: 'Mt',
        name: 'Meitnerium',
        atomic_mass: 278,
        category: 'unknown',
        xpos: 9,
        ypos: 7,
        cpk_hex: 'eb0024',
        phase: 'Solid',
        discovered_by: 'GSI',
        summary: 'Synthetic radioactive element.'
    },
    {
        number: 110,
        symbol: 'Ds',
        name: 'Darmstadtium',
        atomic_mass: 281,
        category: 'unknown',
        xpos: 10,
        ypos: 7,
        cpk_hex: 'null',
        phase: 'Solid',
        discovered_by: 'GSI',
        summary: 'Synthetic radioactive element.'
    },
    {
        number: 111,
        symbol: 'Rg',
        name: 'Roentgenium',
        atomic_mass: 282,
        category: 'unknown',
        xpos: 11,
        ypos: 7,
        cpk_hex: 'null',
        phase: 'Solid',
        discovered_by: 'GSI',
        summary: 'Synthetic radioactive element.'
    },
    {
        number: 112,
        symbol: 'Cn',
        name: 'Copernicium',
        atomic_mass: 285,
        category: 'transition metal',
        xpos: 12,
        ypos: 7,
        cpk_hex: 'null',
        phase: 'Gas',
        discovered_by: 'GSI',
        summary: 'Synthetic radioactive element.'
    },
    {
        number: 113,
        symbol: 'Nh',
        name: 'Nihonium',
        atomic_mass: 286,
        category: 'unknown',
        xpos: 13,
        ypos: 7,
        cpk_hex: 'null',
        phase: 'Solid',
        discovered_by: 'RIKEN',
        summary: 'Synthetic radioactive element.'
    },
    {
        number: 114,
        symbol: 'Fl',
        name: 'Flerovium',
        atomic_mass: 289,
        category: 'post-transition metal',
        xpos: 14,
        ypos: 7,
        cpk_hex: 'null',
        phase: 'Solid',
        discovered_by: 'JINR',
        summary: 'Synthetic radioactive element.'
    },
    {
        number: 115,
        symbol: 'Mc',
        name: 'Moscovium',
        atomic_mass: 290,
        category: 'unknown',
        xpos: 15,
        ypos: 7,
        cpk_hex: 'null',
        phase: 'Solid',
        discovered_by: 'JINR',
        summary: 'Synthetic radioactive element.'
    },
    {
        number: 116,
        symbol: 'Lv',
        name: 'Livermorium',
        atomic_mass: 293,
        category: 'unknown',
        xpos: 16,
        ypos: 7,
        cpk_hex: 'null',
        phase: 'Solid',
        discovered_by: 'JINR',
        summary: 'Synthetic radioactive element.'
    },
    {
        number: 117,
        symbol: 'Ts',
        name: 'Tennessine',
        atomic_mass: 294,
        category: 'unknown',
        xpos: 17,
        ypos: 7,
        cpk_hex: 'null',
        phase: 'Solid',
        discovered_by: 'JINR',
        summary: 'Synthetic radioactive element.'
    },
    {
        number: 118,
        symbol: 'Og',
        name: 'Oganesson',
        atomic_mass: 294,
        category: 'noble gas',
        xpos: 18,
        ypos: 7,
        cpk_hex: 'null',
        phase: 'Solid',
        discovered_by: 'JINR',
        summary: 'Synthetic radioactive element.'
    }
];

export const CATEGORY_COLORS: Record<string, string> = {
    'diatomic nonmetal': '#4ade80',
    'noble gas': '#60a5fa',
    'alkali metal': '#f87171',
    'alkaline earth metal': '#fbbf24',
    metalloid: '#c084fc',
    'polyatomic nonmetal': '#34d399',
    'post-transition metal': '#94a3b8',
    'transition metal': '#f472b6',
    lanthanide: '#a78bfa',
    actinide: '#fb7185',
    unknown: '#525252'
};
